# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-21 01:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0004_auto_20160818_0304'),
    ]

    operations = [
        migrations.AddField(
            model_name='association',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='association',
            name='date_modified',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
