# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-14 19:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0005_auto_20160821_0140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investor',
            name='associations',
        ),
        migrations.RemoveField(
            model_name='investor',
            name='user',
        ),
        migrations.AddField(
            model_name='investor',
            name='association',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='entity.Association'),
        ),
        migrations.AddField(
            model_name='investor',
            name='first_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='investor',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investor',
            name='last_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='association',
            name='founder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
