# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-14 19:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0006_auto_20160914_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='association',
        ),
        migrations.RemoveField(
            model_name='revenue',
            name='association',
        ),
    ]
