# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-14 20:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0008_partner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='association',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='user',
        ),
        migrations.DeleteModel(
            name='Partner',
        ),
    ]
