# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-15 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0011_investor_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='gender',
            field=models.CharField(choices=[('1', 'Masculino'), ('2', 'Femenino')], default='1', max_length=1),
            preserve_default=False,
        ),
    ]
