# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-17 01:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0012_auto_20160915_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='alias',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='investor',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investor',
            name='dni',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='investor',
            name='phohe',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
