# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-17 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0014_auto_20160916_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='image_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
