# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-03 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0015_auto_20160917_1357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investment',
            old_name='money',
            new_name='capital',
        ),
        migrations.AddField(
            model_name='investment',
            name='authorization',
            field=models.PositiveIntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='fee',
            field=models.SmallIntegerField(choices=[(0, 'None'), (1, '1'), (3, '3'), (6, '6'), (12, '12')], default=0),
        ),
        migrations.AddField(
            model_name='investment',
            name='final_capital',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='first_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='investment',
            name='interests',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='investment',
            name='last_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='investment',
            name='warrant',
            field=models.PositiveIntegerField(null=True, unique=True, verbose_name='orden'),
        ),
    ]
