# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-13 15:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0016_auto_20161003_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='monthly_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Importe mensual'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='authorization',
            field=models.PositiveIntegerField(null=True, unique=True, verbose_name='N\xb0 Autorizaci\xf3n'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='capital',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Capital'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='date',
            field=models.DateField(verbose_name='Creaci\xf3n'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='fee',
            field=models.SmallIntegerField(choices=[(1, '1'), (3, '3'), (6, '6'), (12, '12')], default=0, verbose_name='Cuotas'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='final_capital',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Capital final'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='interests',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Intereses'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='investor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entity.Investor', verbose_name='Inversor'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='warrant',
            field=models.PositiveIntegerField(null=True, unique=True, verbose_name='N\xb0 Orden'),
        ),
    ]
