# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-14 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0017_auto_20161013_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fin del prestamo'),
        ),
    ]
