# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 14:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0019_investment_profit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Borrower',
        ),
        migrations.DeleteModel(
            name='Moneylender',
        ),
        migrations.RemoveField(
            model_name='revenue',
            name='investor',
        ),
        migrations.DeleteModel(
            name='Revenue',
        ),
    ]
