# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 04:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0020_auto_20161018_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField(verbose_name='Periodo')),
                ('capital', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prestado')),
                ('payment', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Capital por cuotas')),
                ('recovered', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Recuperado')),
                ('profit', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ganancia')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entity.Investor', verbose_name='Inversor')),
            ],
        ),
    ]
