# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0021_revenue'),
    ]

    operations = [
        migrations.AddField(
            model_name='revenue',
            name='investment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='entity.Investment', verbose_name='Prestamo'),
        ),
    ]
